import React from "react";
import {
  FaJava,
  FaAngular,
  FaReact,
  FaNodeJs,
  FaHtml5,
  FaCss3,
  FaChartLine,
  FaCubes,
  FaMobileAlt,
  FaSass,
  FaBootstrap,
  FaCloudDownloadAlt,
  FaEnvelope,
  FaGitAlt,
  FaDocker,
  FaJenkins,
  FaCogs,
  FaNpm,
  FaFileAlt,
  FaVial,
  FaTachometerAlt,
  FaClipboardCheck,
  FaLock,
  FaIdCard,
  FaShieldAlt,
  FaGithub,
  FaCodeBranch,
} from "react-icons/fa";
import {
  SiJavascript,
  SiTypescript,
  SiSpringboot,
  SiSmartthings,
  SiSolidity,
  SiWeb3Dotjs,
  SiEthereum,
  SiDatabricks,
  SiBlockchaindotcom,
  SiGnuprivacyguard,
  SiReactivex,
  SiNgrx,
  SiRedux,
  SiTailwindcss,
  SiMongodb,
  SiOracle,
  SiMysql,
  SiPostgresql,
  SiApachecassandra,
  SiRabbitmq,
  SiKubernetes,
  SiWebpack,
  SiJira,
  SiAtlassian,
  SiJest,
  SiJasmine,
  SiJsonwebtokens,
  SiKeycloak,
} from "react-icons/si";

const iconMap = {
  SiJavascript,
  SiTypescript,
  FaJava,
  FaAngular,
  FaReact,
  FaNodeJs,
  SiSpringboot,
  FaHtml5,
  FaCss3,
  SiSmartthings,
  SiSolidity,
  SiWeb3Dotjs,
  SiEthereum,
  SiDatabricks,
  SiBlockchaindotcom,
  SiGnuprivacyguard,
  SiReactivex,
  SiNgrx,
  SiRedux,
  FaChartLine,
  FaCubes,
  FaMobileAlt,
  FaSass,
  FaBootstrap,
  SiTailwindcss,
  FaCloudDownloadAlt,
  SiMongodb,
  SiOracle,
  SiMysql,
  SiPostgresql,
  SiApachecassandra,
  FaEnvelope,
  SiRabbitmq,
  FaGitAlt,
  FaDocker,
  SiKubernetes,
  FaJenkins,
  FaCogs,
  SiWebpack,
  FaNpm,
  SiJira,
  SiAtlassian,
  FaFileAlt,
  SiJest,
  SiJasmine,
  FaVial,
  FaTachometerAlt,
  FaClipboardCheck,
  FaLock,
  FaIdCard,
  SiJsonwebtokens,
  SiKeycloak,
  FaShieldAlt,
  FaGithub,
  FaCodeBranch,
};

const TechnologyIcon = ({ icon, className = "" }) => {
  const IconComponent = iconMap[icon];

  if (!IconComponent) {
    console.warn(`Icon not found: ${icon}`);
    return null;
  }

  return <IconComponent className={className} />;
};

export default TechnologyIcon;
